apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-csi-app-set
spec:
  selector:
    matchLabels:
      app: mypod
  serviceName: "my-frontend"
  replicas: 1
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
      - name: my-frontend
        image: busybox
        args:
        - sleep
        - infinity
        volumeMounts:     # voy a montar el csi-pvc en /data
        - mountPath: "/data"
          name: csi-pvc
  volumeClaimTemplates:   # debemos declarar el volumen
  - metadata:
      name: csi-pvc
    spec:
      accessModes:
      - ReadWriteOnce     # para que se pueda escribir
      resources:
        requests:
          storage: 5Gi    # tamaño del disco
      storageClassName: do-block-storage    # storageClass es un driver de kubernetes para un proveedor.
      # Permite crear un volumen o un disco virtual desde kubernetes hacia el proveedor